### ISSUE TITLE
Error with MariaDB opening member profile

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#3049] opened 2017-11-06 20:41 UTC
https://www.elkarte.net/community/index.php?topic=4744

**Comment by albertlast** [comment] 2017-11-07 05:13
In my eyes you use sql key words: https://www.drupal.org/docs/develop/coding-standards/list-of-sql-reserved-words
so you had two choice:
Use " " like already mention in the board or
evade the using of key words.

the last option in my eyes is the better way.

The first option got the down side,
that you had to use " which in general in mysql ` is but sometime not and
pg need " so this adds complexity.

**Comment by albertlast** [comment] 2017-11-07 17:04
ok this option i didn't notice,
but when you already add the cs. to rows why not add this to all this cols in this qry?
Did it somehow hurt?

**Comment by emanuele45** [comment] 2017-11-07 20:50
> Did it somehow hurt?

My fingers typing and my eye starting at all the cs. :laughing: 

On a more serious note: having it only where the problem is, makes more evident where the problem is.
IMO, of course.

**Comment by albertlast** [comment] 2017-11-08 04:59
Well let me add my pov,
when i look at the sql code and see only one col with cs than is me a anomaly and
i more likly to "fix" this (possible fix would be to delete the cs).
When you sometime in furture extend this query with a join than you run maybe in the next issue,
because some of the cols of the other table are the same,
than you add again on some col the cs...

This would be my pov, end of the day it's your (or how ever do the pr)
decision how to realize.

**Comment by emanuele45** [comment] 2017-11-19 11:11
This now should work in 1.1.1 with an ugly workaround.
The proper fix (i.e. not use reserved names for columns) will come in with 2.0.

**Comment by live627** [comment] 2017-12-16 01:00
1.1.1 is now merged in, this can be closed.

**Closed** 2017-12-16 09:59 UTC
Labels: bug, good first issue
