### ISSUE TITLE
registration younger where registration user click i am least 18 years old

### ISSUE THREAD

**Issue by Red-Owl** [elkarte/Elkarte#3362] opened 2019-10-31 21:02 UTC
forum73.com registration user set to younger where user click >18years

**Comment by Spuds** [comment] 2019-10-31 23:01
Something else to consider addressing in 2.0, but that registration code is a bit convoluted due to all of the options.

Anyway I think this issue is caused by the use of the registration checkbox with coppa, I think the full registration page with coppa would work fine.

The fix for this is to find this section 
```
		// If we're using an agreement checkbox, did they check it?
		if (!empty($modSettings['checkboxAgreement']) && !empty($this->_req->post->checkbox_agreement))
			$_SESSION['registration_agreed'] = true;

		// Well, if you don't agree, you can't register.
```

and replace it with  this which adds a coppa / registration checkbox check section:
```
		// If we're using an agreement checkbox, did they check it?
		if (!empty($modSettings['checkboxAgreement']) && !empty($this->_req->post->checkbox_agreement))
			$_SESSION['registration_agreed'] = true;

		// Using coppa and the registration checkbox?
		if (!empty($modSettings['coppaAge']) && !empty($modSettings['checkboxAgreement']) && !empty($this->_req->post->accept_agreement))
			$_SESSION['skip_coppa'] = true;

		// Well, if you don't agree, you can't register.
```
 to Register.controller.php (in the sources/controller directory)

**Closed** 2020-01-07 01:47 UTC
Labels: bug
