### ISSUE TITLE
Unknown column 'id_msg' in 'where clause'

### ISSUE THREAD

**Issue by ghost** [elkarte/Elkarte#3103] opened 2018-01-22 21:07 UTC
Hi Developers,

I found a bug when deleting a topic. I use ElkArte 1.0.11 and just wanted to delete a topic, but unfortunately this error is displayed.

`Unknown column 'id_msg' in 'where clause'
Datei: /xxxxxxxxxxxxxxxxxxxxxx/liebrechts-portfolio.de/elkarteforum.liebrechts-portfolio.de/sources/subs/Topic.subs.php
Zeile: 332`

How can I fix it?

Thanks in advance.

**Comment by emanuele45** [comment] 2018-01-22 21:24
Hi @AlexL777 I think you mean 1.0.10? Because 1.0.11 doesn't exist yet and the line number matches that of 1.0.10.
hmm... that's odd, could you please verify in your Topics.subs.php which one is the query just **before** line 332?
As a quick workaround I think you can enable the recycle board, this way the topic will just be moved there, so the problematic code will not be called and you'll be able to at least remove the topic from the public view.

**Comment by emanuele45** [comment] 2018-01-22 21:26
As a general consideration: seems a strange situation, that column is there since... almost the beginning of 1.0 development, I'm not sure how it could be missing from your database unless of some other issue in the meantime.

**Comment by AlexL777** [comment] 2018-01-22 21:33
Thanks, so no bug, because your first hints helped. I have activated the deleted topic board and I've been able to delete the topic.

Unfortunately, I did not know that yet.

So the problem is solved and you can close the issue now.

Thank you!

**Comment by emanuele45** [comment] 2018-01-22 21:38
This is more a workaround than a fix, the issue is still there, just hidden. ;)

**Comment by AlexL777** [comment] 2018-01-22 21:40
Oh so ok. Then it's still a bug. So far I have not paid attention and did not have to delete any topics, but today I clean up in the forum. For me, the problem is solved for the first time, but if it is still a bug, then probably fixed.

**Comment by emanuele45** [comment] 2018-01-22 21:54
Well, the problem is likely to be in your install, I just wanted to help you debug the issue. :smile:

**Comment by AlexL777** [comment] 2018-01-22 21:59
I thank you for the rapid help and now everything is fine again. I have moved ElkArte Board v1.0.10 several times and imported the databases. Maybe something went wrong.

**Closed** 2024-04-03 14:30 UTC
Labels: not-a-bug/support
