### ISSUE TITLE
If registration fails, the agreement causes a db failure

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#3278] opened 2019-01-03 07:48 UTC
https://www.elkarte.net/community/index.php?topic=5510.0

I put also a fix in the topic.
In short: the "accept agreement and policy" should be moved *after* the errors check, so that we are *sure* $memberID is actually an integer and not a boolean.

**Comment by VBGAMER45** [comment] 2019-01-03 20:17
Looks like duplicate of https://github.com/elkarte/Elkarte/issues/3236

**Comment by emanuele45** [comment] 2019-03-22 20:02
Yep, indeed looks like a duplicate. Thanks @VBGAMER45

**Closed** 2019-03-22 20:02 UTC
Labels: block, bug, duplicate, good first issue
