### ISSUE TITLE
If age restriction is enabled registration fails

### ISSUE THREAD

**Issue by emanuele45** [elkarte/Elkarte#3134] opened 2018-03-17 20:34 UTC
This affects the development version.
1. require agreement
2. have age restriction enabled
3. try to register
4. click on "accept and I'm over xx years old
=> expected: register
=> observed: "Sorry, but users under the age of 13 are not allowed to register on this forum."

**Comment by Spuds** [comment] 2024-04-03 21:01
Unable to reproduce on current dev .... although there were other errors that were fixed in the About PR

**Closed by Spuds** 2024-04-03 21:01 UTC
Labels: bug
