### ISSUE TITLE
Undefined index: attachmentUploadDir

### ISSUE THREAD

**Issue by interlab** [elkarte/Elkarte#3346] opened 2019-09-15 15:02 UTC
Undefined index: attachmentUploadDir
index.php?action=admin;area=manageattachments;save;sa=attachments
sources/admin/ManageAttachments.controller.php
ElkArte 1.1.6
php 7.2.6

**Comment by interlab** [comment] 2019-09-17 17:20
I think it's just me that's the problem

**Comment by interlab** [comment] 2019-09-18 04:59
this issue occurs if javascript is disabled

**Comment by Spuds** [comment] 2019-09-18 13:22
Thank you for the debug

**Comment by Spuds** [comment] 2020-12-10 19:54
I have not been able to reproduce this on 1.1.7 ... I've tried fresh install's with and with out JS enabled.  I don't know if this was fixed somewhere along the line or if there is something else amiss

**Comment by interlab** [comment] 2020-12-12 08:40
php 7.1, js is disabled, branch - 1.1.7:

![image](https://user-images.githubusercontent.com/2246621/101978796-5ffee780-3c60-11eb-9d79-fdb92876e245.png)

to catch the error, you need to go to the page "index.php?action=admin;area=manageattachments;sa=attachments;" and enable the parameter "Check attachment's extension":

![image](https://user-images.githubusercontent.com/2246621/101979439-cc301a00-3c65-11eb-992d-038abb8f33b4.png)

**Comment by Spuds** [comment] 2020-12-22 01:57
Thanks, that helped .... 

The issue is that the option  ```Create new directories within a base directory``` is always visible when JS is off, but its really only a valid option when not in "manual" mode.  Its easy to suppress the error, but I need to understand what JS is doing to set defaults before I do anything.   

@emanuele45 we need to REQUIRE js in the ACP in 2.0, this is nuts

**Comment by Spuds** [comment] 2020-12-22 03:05
I think I've found a logic issue in the flow, not sure yet since that area of the code is .. yeah !  Will check again in the AM since I'm to tired to look at this anymore tonight! ...

**Comment by Spuds** [comment] 2020-12-23 15:18
Here is a patch to try, or just gab the file and give it a test.   I know I fixed several issues but have not done enough w/o JS testing.

https://github.com/Spuds/Elkarte/commit/89e50d26889fc63e6011f8a83ea7ffb6d45851aa

**Comment by interlab** [comment] 2020-12-25 06:42
now there are no errors

**Comment by Spuds** [comment] 2020-12-26 22:50
Seems like this was fixed in https://github.com/elkarte/Elkarte/commit/89e50d26889fc63e6011f8a83ea7ffb6d45851aa

**Closed by Spuds** 2020-12-26 22:50 UTC
Labels: bug
