### ISSUE TITLE
Headers already sent in ScheduledTasks.controller.php

### ISSUE THREAD

**Issue by Vekseid** [elkarte/Elkarte#2391] opened 2016-02-26 06:55 UTC
Lines 74-76

This is an ancient bug, present in SMF. >_>

**Comment by emanuele45** [comment] 2016-02-26 08:25
Some hint on specific cases it happens?
Lines 74 to 76 of the controllers are an if an an empty line, those should never complain about headers... :-\

Ohhh... you mean 1.1? Sorry, I thought you were talking about 1.0.

The best I can imagine is that it reacts to another error already send out (maybe). Could you check in the scheduled tasks log if there is one failing?

**Comment by Vekseid** [comment] 2016-02-26 18:08
This obviously is not a big bug. It has however generated a decent fraction of a billion lines in my error logs -_-

**Comment by Spuds** [comment] 2016-10-01 21:10
Looks like the lines have moved .. was this the call to ```dieGif(true)```? If so we could use a simple ```!headers_sent()``` to prevent the error log spam, not a fix but a block.   Could also do a  ```(!headers_sent($filename, $linenum))``` and log when it fails so we can better see whats getting called first.

**Comment by Vekseid** [comment] 2016-10-02 21:25
Got moved here:
https://github.com/elkarte/Elkarte/commit/7aed48e3d6dd547cc162af2e2fd9ad5e3016d9f3

Though I'm not sure if the issue got addressed properly. @emanuele45 ?

**Comment by emanuele45** [comment] 2016-10-02 21:55
Indeed.
7aed48e3d6dd547cc162af2e2fd9ad5e3016d9f3 is just a moving things around, never meant to fix anything.
It would be very useful to find out when headers are sent out the first time...

**Comment by Spuds** [comment] 2016-10-03 00:35
Best we can do is ask someone who is seeing the error to also log it to the Elk error log using ```headers_sent($filename, $linenum)``` plus logerror  that should let us know where its happening.   Since the purpose of the function is to keep the connection alive, I guess if headers are already sent in some cases,  we could just check for that, flush and go

**Comment by emanuele45** [comment] 2016-10-04 12:11
I have the feeling it may happen in case of errors... maybe database errors, but it's based on nothing at all...

**Comment by Spuds** [comment] 2016-10-04 13:09
Humm I bet thats true ... at which point we can't really "stop" that, but checking if the headers were sent before sending  even more would at least stop filling up the server error log.

**Comment by emanuele45** [comment] 2016-10-07 11:14
I added the logging code, without localization and with a note to remove the code when this bug is fixed.

**Comment by emanuele45** [comment] 2016-10-21 08:51
Moved to 2.0 with the meaning of "when the proper error will be reported, the bug will be fixed and the issue closed". Not because I was to ignore it. :smile:

**Comment by emanuele45** [comment] 2018-05-04 06:38
https://www.elkarte.net/community/index.php?topic=5182.0

The problem is the fastcgi_finish_request call introduced a while ago.
The possible solutions I see are:
# drop the fastcgi_finish_request call
# drop the gif header and just send an empty page

**Comment by Spuds** [comment] 2018-05-04 12:51
Or don't call dieGif from the autotask method if you have called fastcgi_finish_request and closed the connection?
```
		if (!function_exists('fastcgi_finish_request'))
			dieGif(true);
```

**Comment by Spuds** [comment] 2018-05-08 12:58
On second thought (and test) ... I'd say drop the call.

**Comment by Vekseid** [comment] 2018-05-10 02:12
The reason I added it is because if you have any meaningful forum members can end up waiting several minutes for the request to finish.

It could be optional, but it is deathly necessary for any sufficiently massive forum.

**Comment by Spuds** [comment] 2018-05-21 13:14
Interesting ...  maybe for now we just do a 
```
	if (function_exists('fastcgi_finish_request'))
	{
		die();
	}
```
at the start of ```dieGif()```

**Comment by emanuele45** [comment] 2018-05-21 19:40
Makes sense I guess.

**Comment by emanuele45** [comment] 2018-05-22 07:02
Well, at least for now, considering it's not likely to be terribly widespread, to me works.
For later we can think about something different. :+1:

**Comment by Spuds** [comment] 2018-05-31 15:27
Did what we could for 1.1.4, moving this to 2.0 for any further action

**Closed** 2018-12-09 14:43 UTC
Labels: bug
