### ISSUE TITLE
array to string error

### ISSUE THREAD

**Issue by Spuds** [elkarte/Elkarte#2134] opened 2015-07-19 11:28 UTC
Type of error: General
Array to string conversion
http://www.elkarte.net/community/index.php?action=register2
File: /.../community/sources/ext/bad-behavior/badbehavior-plugin.php
Line: 193

**Comment by emanuele45** [comment] 2015-07-20 19:01
Do you have any idea why this is happening?

**Comment by Spuds** [comment] 2015-07-20 21:36
I'd guess that implode only words on a single dimensional array ... so POST must be an array of arrays, or at least one key of the array is not a value but another array.  I guess serialize may work ... but looking at that code there is no size check on the the POST data that may get inserted either.  Still "easy" to fix, but may require a db scheme change :/   So not sure how to proceed really.

**Comment by emanuele45** [comment] 2015-07-20 22:08
I wonder what changed to get this error though.
I don't think we did any change to the registration page or verification code... unless I'm wrong.

**Comment by Spuds** [comment] 2015-07-21 01:16
Does it happen every time on action register2 ? 

It could just be that it was legitimate bad behavior being flagged/blocked (bot or other trying to pump that function) and then during the logging of the POSTed data for "info" its failing.

**Comment by emanuele45** [comment] 2015-07-22 09:20
Ouch, duplicate of #2105 
I'll close the other since the discussion is going on here.

**Comment by emanuele45** [comment] 2015-07-22 09:23
> Does it happen every time on action register2 ? 

I don't think it even happen when a user is registering...
I have in my inbox a couple of new members on the 19th, but in the log there is an error dated 20th, so it's probably unrelated... :-\

**Comment by Spuds** [comment] 2015-07-22 10:46
Makes sense (thats its a legit BB block) ... Do you think its even worth logging what was posted anyway?

**Comment by emanuele45** [comment] 2015-07-22 11:07
hmm... what could you use that info for?
The only thing I can think of is to ban or deny registration to anyone posting a certain "something" (so logging what was posted may be an indication), but such a method is not likely to be that reliable anyway. I think.

**Comment by Spuds** [comment] 2015-07-22 14:10
Probably not very useful in real terms, just a curiosity.  Like in this instance it would have been interesting to see what they were using on the registration form.  

That said a post can contain a lot of data so if we keep that capability the db scheme should be changed to hold more, and even then the code will need to check if it will fit.   The header code does that and selectively logs what may be useful for banning etc, its a bit clunky but TBH some of it is logging just because we can vs a real need.

**Comment by emanuele45** [comment] 2015-07-25 20:00
Confirmed: it's with bots and not with real humans.

For how to fix it and if it is necessary of not, up to you. ;D

**Closed** 2015-08-10 18:39 UTC
Labels: block, bug, easy
