### ISSUE TITLE
_setup_editor() not called (possibly PHP7)

### ISSUE THREAD

**Issue by Frenzie** [elkarte/Elkarte#2502] opened 2016-04-21 09:55 UTC
I have mentions enabled (although the setting and the user-facing text have different names).

For the rich text editor, `$context['mentions_enabled']` is always empty.

```
		// Mentions?
		if (!empty($context['mentions_enabled']))
			loadJavascriptFile(array('jquery.atwho.min.js', 'jquery.caret.min.js', 'mentioning.plugin.js'));
```

For the simple one, _setup_editor() doesn't seem to be called in any way.

I don't quite grasp the structure of the whole thing at this time, so I'm not really sure how to debug.

**Comment by emanuele45** [comment] 2016-04-21 18:06
Yeah, that part is probably a little overengineered...

Can you give a little more context?
Are you doing a clean install or an upgrade?

The problem is most likely that in the settings table, the setting ```modules_post``` is missing the entry ```mentions```.
Could you check if this is the case? It's a comma separated list of names.
If it is not there, then the question is: why it is not there? :stuck_out_tongue: 
If coming from a fresh install you may have hit #2440 if an upgrade it may be something broken with the upgrade script.

**Comment by Frenzie** [comment] 2016-04-21 18:35
Unless otherwise specified, always clean. Testing upgrades is a whole different can of worms. =P

`poll,attachments,verification,random` (this is also after saving it in the settings)

Adding it to `modules_display` and `modules_post` manually indeed works.

**Comment by emanuele45** [comment] 2016-06-02 21:10
This is indeed the same as #2440 so closing as duplicate (and because the other is going to be fixed).

**Closed by emanuele45** 2016-06-02 21:10 UTC
Labels: block, bug
