### ISSUE TITLE
One click email unsubscribe

### ISSUE THREAD

**Issue by Trekkie101** [elkarte/Elkarte#2824] opened 2017-01-10 10:48 UTC
Emails should have a one click unsubscribe button that allows even a non logged in user to unsubscribe from any or all emails. 

Usually its achieved by giving each user a unique 'key' like a hash that when clicked unsubscribe.php?id=mkfdnd0d0ygd8g8gd987

**Comment by live627** [comment] 2018-01-20 23:54
Duplicate of https://github.com/elkarte/Elkarte/issues/2446

**Closed** 2018-01-21 09:33 UTC
Labels: feature request
